// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApp.Infrastructure;

#nullable disable

namespace RestaurantApp.Infrastructure.Migrations
{
    [DbContext(typeof(RestaurantAppDbContext))]
    [Migration("20260610200421_AddedSeededDemoData")]
    partial class AddedSeededDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AlcoholPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrinkTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<int>("Millilitres")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkTypeId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.DrinkOrder", b =>
                {
                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("DrinkId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("DrinksOrders");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.DrinkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("DrinkTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(782),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(783),
                            Name = "Топли"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(784),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(785),
                            Name = "Студени"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(785),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(786),
                            Name = "Коктейли"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(786),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(787),
                            Name = "Вина"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(787),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(787),
                            Name = "Бири"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("NetGrams")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.FoodOrder", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("FoodsOrders");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(680),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(681),
                            Name = "Салати"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(682),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(682),
                            Name = "Предястия"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(683),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(683),
                            Name = "Основни"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(684),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(684),
                            Name = "Гарнитури"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(685),
                            Modified = new DateTime(2026, 6, 10, 20, 4, 20, 384, DateTimeKind.Utc).AddTicks(685),
                            Name = "Десерти"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashsedToken")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<int>("TerminalTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalTypeId");

                    b.ToTable("Terminals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Main cashier terminal",
                            HashedSecret = "3b433ce50731ea6c64d1bf7b35f3f741a300c5ba4feb81fdfcbf248d09a318aa",
                            IsLockedOut = false,
                            TerminalTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Main kitchen terminal",
                            HashedSecret = "3500d04ae3acd5b19ac48edfaa1b1e7dba48b7f3a5c2891c063c6a549957f8f5",
                            IsLockedOut = false,
                            TerminalTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Main client terminal",
                            HashedSecret = "e8ddf15adc116024cf009d842546a6a3f307e9fac04f7721d58b8baf9f416cac",
                            IsLockedOut = false,
                            TerminalTypeId = 3
                        });
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.TerminalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerminalTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An administrative terminal for handling payments and managing the menu.",
                            Name = "Cashier"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A terminal for managing orders in a kitchen.",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A client terminal for making orders.",
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Drink", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.DrinkType", "DrinkType")
                        .WithMany("Drinks")
                        .HasForeignKey("DrinkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrinkType");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.DrinkOrder", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Domain.Entities.Order", "Order")
                        .WithMany("DrinksOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Food", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.FoodType", "FoodType")
                        .WithMany("Foods")
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.FoodOrder", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.Food", "Food")
                        .WithMany("FoodOrders")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Domain.Entities.Order", "Order")
                        .WithMany("FoodsOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Terminal", b =>
                {
                    b.HasOne("RestaurantApp.Domain.Entities.TerminalType", "TerminalType")
                        .WithMany()
                        .HasForeignKey("TerminalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminalType");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.DrinkType", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Food", b =>
                {
                    b.Navigation("FoodOrders");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.FoodType", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("RestaurantApp.Domain.Entities.Order", b =>
                {
                    b.Navigation("DrinksOrders");

                    b.Navigation("FoodsOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
